services:
  backend-rails:
    build:
      context: ./rails
    container_name: management_screens-backend-rails
    env_file:
      - .env
    depends_on:
      database-mysql:
        condition: service_started
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    restart: always
    networks:
      - management_network

  database-mysql:
    container_name: management_screens-db-mysql
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - mode: ingress
        target: 3306
        published: "3309"
        protocol: tcp
    restart: always
    volumes:
      - management_db:/var/lib/mysql
      - ./.docker/mysql/logs:/var/log/mysql
    networks:
      - management_network

volumes:
  management_db:

networks:
  management_network: