services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend_rails
    restart: always
    networks:
      - management_network

  backend_rails:
    build:
      context: .
      dockerfile: ./.docker/rails/Dockerfile
      args:
        SECRET_KEY_BASE: $$SECRET_KEY_BASE
        RAILS_ENV: $$RAILS_ENV
    volumes:
      - ./rails:/usr/src/app
    env_file:
      - .env
    depends_on:
      database_mysql:
        condition: service_started
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    restart: always
    networks:
      - management_network

  database_mysql:
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - mode: ingress
        target: 3306
        published: "3309"
        protocol: tcp
    restart: always
    volumes:
      - management_db:/var/lib/mysql
    networks:
      - management_network

volumes:
  management_db:


networks:
  management_network:
